### ISSUE TITLE
ORC 2.0 double compression

### ISSUE THREAD

**Issue by omalley** [mojodna/osm-pds-pipelines#1]
The ORC project is looking at improving the float/double compression with a new set of encodings. 

Do you have any feedback? I'll pull some of your data to use it as sample data to guide our design.

**Comment by mojodna** [comment]
Sorry for the delay. Thank you for checking!!

No, no feedback. Everything has worked as expected and I haven't been close enough to the queries to see performance implications of the current encodings.
