### ISSUE TITLE
Implementing functions/changes-json

### ISSUE THREAD

**Issue by kamicut** [mojodna/osm-pds-pipelines#2]
Per our discussion off repo, I'll be working on a `changes-json` lambda function that has the same functionality as `changes-xml` but outputs json using [osm2obj](https://github.com/digidem/osm2obj).

Since osm2obj doesn't seem to handle the changesets case, what are your thoughts on how to handle a `changesets-json` and a json format for changesets? Add something to `osm2obj`, or rip the parser from `planet-stream` and add it here?

**Comment by mojodna** [comment]
`osm2obj` does support changesets.

**Comment by kamicut** [comment]
You're right, I got it to work.
