### ISSUE TITLE
unable to access s3://osm-pds

### ISSUE THREAD

**Issue by jsiddharth** [mojodna/osm-pds-pipelines#21]
https://aws.amazon.com/public-datasets/osm/ does not mention anything about the AWS access key.

When I run 
aws s3 ls osm-pds

I get the following error

An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.

**Comment by mojodna** [comment]
The `aws` command line tool assumes that you've provided it with credentials (via various mechanisms, the easiest of which is probably `aws configure`). If it doesn't have credentials, none of the sub-commands will work (including `s3 ls`).
