### ISSUE TITLE
OSM AWS Athena Tables Not Updated

### ISSUE THREAD

**Issue by ojasgupta1** [mojodna/osm-pds-pipelines#41]
The OSM Athena Tables get updated every week on Sunday, but this week they didn't got updated, the planet-latest.orc was last updated on 5-June-2022.
https://s3.console.aws.amazon.com/s3/buckets/osm-pds?region=us-east-1&prefix=planet/&showversions=false

**Comment by mojodna** [comment]
See #40 for the cause. It's been re-synced and is transcoding the correctly-sized PBFs now. The Athena tables should be updated in ~6-12 hours.
