### ISSUE TITLE
History Latest Not Updated in OSM-PDS S3 Bucket

### ISSUE THREAD

**Issue by ojasgupta1** [mojodna/osm-pds-pipelines#42]
history-latest.orc in planet-history not updated for this week, The last updated date for history-latest. orc is showing as June 20, 2022. 
Link: https://s3.console.aws.amazon.com/s3/buckets/osm-pds?region=us-east-1&prefix=planet-history/&showversions=false

**Comment by mojodna** [comment]
There appears to have been a delay in production of last week's history file (for June 27th). It's being processed now, and should appear later today.
