### ISSUE TITLE
Planet Latest Not Updated in OSM-PDS S3 Bucket

### ISSUE THREAD

**Issue by ojasgupta1** [mojodna/osm-pds-pipelines#43]
planet-latest.orc file not updated in planet folder of OSM-PDS S3 Bucket, The last updated data is shown as July 16, 2022.
Link: https://s3.console.aws.amazon.com/s3/object/osm-pds?region=us-east-1&prefix=planet/planet-latest.orc

**Comment by mojodna** [comment]
The transcoded version in `2022/` was truncated. I've re-queued the transcoding job and it should be in place in about 10 hours.

**Comment by mojodna** [comment]
This is now updated.
