### ISSUE TITLE
Unable to unsubscribe Lambda Function 

### ISSUE THREAD

**Issue by grfortun** [mojodna/osm-pds-pipelines#44]
I subscribed to the SNS topic with my Lambda function.
I am now unable to remove the SNS subscription as the Lambda trigger. 
I assume the when removing the trigger it first lists SNS subscriptions then matches it before calling the Unsubscribe with my subscription ARN. 
![ExternalSNSdeleteissue](https://user-images.githubusercontent.com/115022357/193852710-2e3e9d17-a85d-4312-be9a-d2c3782831d0.png)

**Comment by mojodna** [comment]
This is likely an issue with the IAM policy associated with your active role. Check that it contains `sns:istSubscriptionsByTopic` (or an `sns:*` wildcard of some sort). This is not a problem with the account hosting the topic (+ S3 bucket).
