### ISSUE TITLE
planet-230313.osm.pbf may break

### ISSUE THREAD

**Issue by smellman** [mojodna/osm-pds-pipelines#45]
planet-230313.osm.pbf may break.
```
$ md5sum planet-230313.osm.pbf # downloaded from s3
068f06d4091c2562c93fd32a52c43025  planet-230313.osm.pbf
$ cat planet-230313.osm.pbf.md5 
ada6d900595c265cf3d4d882f731cbcc  planet-230313.osm.pbf
```
Please re-sync pbf file.

**Comment by mojodna** [comment]
This was successfully transformed into an ORC file, so it looks ok. I'll delete and re-sync the PBF + MD5 files to ensure correctness though.
